# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#      $latestRelease = Invoke-WebRequest https://github.com/docker/buildx/releases/latest -Headers @{"Accept"="application/json"}
#      $json = $latestRelease.content | ConvertFrom-Json
#      $latestVersion = $json.tag_name
#      
#      $outputFolder = [environment]::GetFolderPath('UserProfile') | Join-Path -ChildPath '.docker' | Join-Path -ChildPath 'cli-plugins'
#      new-item -ItemType Directory -Path $outputFolder -Force
#      $outputPath = Join-Path $outputFolder -ChildPath 'docker-buildx.exe'
#      
#      $url = "https://github.com/docker/buildx/releases/download/$latestVersion/buildx-$latestVersion.windows-amd64.exe"
#      Invoke-WebRequest $url -OutFile $outputPath
#    showWarnings: true
#    pwsh: true
#- task: CmdLine@2
#  inputs:
#    script: 'docker buildx install'

- task: CmdLine@2
  displayName: Build      
  inputs:
    script: 'docker buildx bake docker buildx bake cross'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CopyPublishBuildArtifacts@1
  displayName: Publish      
  inputs:
    CopyRoot: '$(Build.SourcesDirectory)/build'
    Contents: 'docker-*'
    ArtifactName: 'drop'
    ArtifactType: 'Container'

#- task: CmdLine@2
#  inputs:
#    script: 'docker buildx uninstall'
